version: 2
jobs:
  build:
    working_directory: ~/halyard.js
    docker:
      - image: circleci/node:12.19.1
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit testing
          command: |
            npm run test:unit
            if [ ! -z "$COVERALLS_REPO_TOKEN" ]; then
              echo "Uploading coverage results to coveralls.io..."
              cat ./coverage/lcov.info | npx coveralls
            fi
      - run:
          name: Check if API specification should be updated
          command: |
            npm run generate:spec
            git diff --exit-code --name-only docs/api-spec.json
      - store_artifacts:
          path: dist
