version: 2
jobs:
  build:
    working_directory: ~/halyard.js
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --no-save -s
      - run:
          name: Build
          command: npm run build
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit testing with coverage
          command: npm run test:unit
      - run:
          name: Publish coverage artifacts to coverall
          command: npm run coverage
      - store_artifacts:
          path: dist
